query GetGoods {
  categories {
    id
    slug
    title
    goods_items {
      id
      image
      description
      price
      shortName
      title
      category_id
    }
  }
}

