query GetGoods {
  categories {
    id
    slug
    title
    goods_items {
      category_id
      description
      id
      image
      price
      shortName
      title
      ingredients
      characteristics
    }
  }
}
